# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [41]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
g_key = 'AIzaSyAoZFHkCidaXiLGl3raC8vHIb6mnzRI51A'
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [90]:

import csv
from pandas.core.frame import DataFrame
import pandas as pd

temp = []
with open('F:/camp/hw/hw6/starter_code/output_data/22.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        temp.append(row)
# tmp_lst        
weather_df = pd.DataFrame(temp[1:], columns=temp[0]) 
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Puerto del Rosario,28.5,-13.86,296.15,78,20,1,ES,1592427735
1,Carnarvon,-24.87,113.63,293.15,100,75,2.1,AU,1592427403
2,Nanortalik,60.14,-45.24,277.05,76,99,3.98,GL,1592427397
3,Tautira,-17.73,-149.15,301.15,74,75,3.6,PF,1592427431
4,Hermanus,-34.42,19.23,283.15,84,2,3.19,ZA,1592427402

In [3]:
heatmap_data = weather_df[['Lat','Lng','Humidity']]
heatmap_data.head()
# type(weather_df['Humidity'][0])
# heatmap_data['Humidity'] = heatmap_data['Humidity'].apply(float)

      Lat      Lng Humidity
0    28.5   -13.86       78
1  -24.87   113.63      100
2   60.14   -45.24       76
3  -17.73  -149.15       74
4  -34.42    19.23       84

In [4]:
heatmap_data['Humidity'] = heatmap_data['Humidity'].apply(float)
heatmap_data['Lat'] = heatmap_data['Lat'].apply(float)
heatmap_data['Lng'] = heatmap_data['Lng'].apply(float)

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [5]:
type(heatmap_data['Humidity'][0])
heatmap_data.head()

     Lat     Lng  Humidity
0  28.50  -13.86      78.0
1 -24.87  113.63     100.0
2  60.14  -45.24      76.0
3 -17.73 -149.15      74.0
4 -34.42   19.23      84.0

In [6]:
type(heatmap_data['Lat'][0])

numpy.float64

In [7]:
locations = heatmap_data[['Lat', 'Lng']]
weights = heatmap_data['Humidity']
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(height='420px'))

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [91]:
weather_df.dropna()
weather_df.head()
weather_df['Max Temp'] = weather_df['Max Temp'].apply(float)
weather_df['Wind Speed'] = weather_df['Wind Speed'].apply(float)
weather_df['Cloudiness'] = weather_df['Cloudiness'].apply(float)

In [92]:
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735
1,Carnarvon,-24.87,113.63,293.15,100,75.0,2.10,AU,1592427403
2,Nanortalik,60.14,-45.24,277.05,76,99.0,3.98,GL,1592427397
3,Tautira,-17.73,-149.15,301.15,74,75.0,3.60,PF,1592427431
4,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402

In [94]:
# A max temperature lower than 300 degrees but higher than 200.
cleaned_data = weather_df[(weather_df['Max Temp']>=200)&(weather_df['Max Temp']<=300)&(weather_df['Wind Speed']<=10)&(weather_df['Cloudiness']<=50)]
     

# Wind speed less than 10 mph.


# cloudiness <50%
cleaned_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735
4,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402
5,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264
7,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425
8,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735

In [95]:
# the temp*************
the_temp= cleaned_data

In [58]:
heatmap_data = cleaned_data[['Lat','Lng','Humidity']]
heatmap_data.head()
heatmap_data['Humidity'] = heatmap_data['Humidity'].apply(float)
heatmap_data['Lat'] = heatmap_data['Lat'].apply(float)
heatmap_data['Lng'] = heatmap_data['Lng'].apply(float)
locations = heatmap_data[['Lat', 'Lng']]
weights = heatmap_data['Humidity']
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
E:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
E:\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [96]:
# {
# html_attributions: [ ],
# results: [ ],
# status: "ZERO_RESULTS" or 'OK'
# }
cleaned_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735
4,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402
5,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264
7,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425
8,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735

In [97]:
cleaned_data['hotel']=0
cleaned_data.dropna().head()

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,hotel
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735,0
4,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402,0
5,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264,0
7,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425,0
8,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735,0

In [101]:
cleaned_data.reset_index(inplace=True,drop=True)
# cleaned_data.dropna()
cleaned_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,hotel
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735,0
1,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402,0
2,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264,0
3,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425,0
4,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735,0

In [105]:
# temp_01 = cleaned_data
# cleaned_data = temp01
temp = cleaned_data
temp.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,hotel
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735,0
1,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402,0
2,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264,0
3,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425,0
4,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735,0

In [106]:
import time
# Make a request for each of the indices
for x in range(len(temp)):
    try:
        print('*/'*10)
        the_lat = temp['Lat'][x]
        the_lng = temp['Lng'][x]
        url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location='+str(the_lat)+','+str(the_lng)+'&radius=5000&type=restaurant&key=AIzaSyAoZFHkCidaXiLGl3raC8vHIb6mnzRI51A'
        
        # Get one of the posts
        post_response = requests.get(url).json()

    except:
        print('**'*15)
        print("** can not find this root **")
        print('**'*15)
        temp.loc[x,'hotel'] = 'no hotel here*'
    else:
        if str(post_response['status']) == 'OK':
            temp.loc[x,'hotel'] = post_response['results'][0]['name']
            time.sleep(1)
        else:
            temp.loc[x,'hotel'] = 'no hotel here'
temp.head()

*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/
*/*/*/*/*/*/*/*/*/*/

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,hotel
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735,Lanzazkoyen S.L.
1,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402,Steers
2,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264,Falls Hotel
3,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425,Cheiro Guloso
4,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735,Diamond Beach Village

In [107]:
temp

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,hotel
0,Puerto del Rosario,28.5,-13.86,296.15,78,20.0,1.00,ES,1592427735,Lanzazkoyen S.L.
1,Hermanus,-34.42,19.23,283.15,84,2.0,3.19,ZA,1592427402,Steers
2,Mataura,-46.19,168.86,277.04,83,0.0,1.34,NZ,1592427264,Falls Hotel
3,Lata,40.16,-8.33,289.82,73,0.0,1.79,PT,1592427425,Cheiro Guloso
4,Lamu,-2.27,40.9,298.60,80,44.0,9.24,KE,1592427735,Diamond Beach Village
5,Ibitinga,-21.76,-48.83,299.15,57,1.0,3.60,BR,1592427526,Victoria Park Hotel e Restaurante
6,Busselton,-33.65,115.33,283.71,58,9.0,8.79,AU,1592427219,Baudins
7,Punta Arenas,-53.15,-70.92,273.15,84,0.0,2.60,CL,1592427328,Yellow Submarine
8,Jamestown,42.1,-79.24,299.26,39,1.0,3.60,US,1592427121,Subway
9,Rikitea,-23.12,-134.97,297.29,79,23.0,6.91,PF,1592427204,no hotel here
10,Arde艧en,41.19,40.99,294.15,88,20.0,3.10,TR,1592427739,Timya Lokantacılık
11,Hervey Bay,-25.3,152.85,288.71,87,1.0,3.60,AU,1592427426,Best Western Ambassador Motor Lodge
12,Geraldton,-28.77,114.6,290.15,77,40.0,9.80,AU,1592427404,Hospitality Geraldton
13,Salinas,36.68,-121.66,299.15,34,1.0,6.20,US,1592427713,In-N-Out Burger
14,Port Elizabeth,-33.92,25.57,283.15,93,0.0,1.00,ZA,1592427403,Bhakti Lounge
15,Yellowknife,62.46,-114.35,289.26,43,40.0,7.70,CA,1592427133,Boston Pizza
16,Portland,45.52,-122.68,294.26,52,40.0,3.10,US,1592427270,The Paramount Hotel Portland
17,Vila Franca do Campo,37.72,-25.43,291.15,72,20.0,6.70,PT,1592427423,Pestana Bahia Praia
18,Ushuaia,-54.8,-68.3,276.15,74,40.0,1.50,AR,1592427219,Hotel Cap Polonio
19,Kaitangata,-46.28,169.85,279.82,60,11.0,2.24,NZ,1592427411,Crescent Bar & Grill
20,Valkeakoski,61.26,24.03,294.26,64,3.0,2.10,FI,1592427741,Papachi Kebab Pizzeria
21,S茫o Jo茫o da Barra,-21.64,-41.05,296.15,69,20.0,4.60,BR,1592427436,Boller Lanchonete
22,Guerrero Negro,27.98,-114.06,296.72,49,0.0,7.42,MX,1592427442,Restaurant Bar Santo Remedio
23,Hobart,-42.88,147.33,274.82,82,20.0,4.60,AU,1592427350,Hotel Grand Chancellor Hobart
24,Puksoozero,62.59,40.61,280.74,62,0.0,1.38,RU,1592427741,no hotel here
25,Ostrovnoy,68.05,39.51,278.15,76,0.0,1.91,RU,1592427411,no hotel here
26,Upernavik,72.79,-56.15,274.94,86,0.0,2.14,GL,1592427403,no hotel here
27,Yar-Sale,66.83,70.83,275.71,81,7.0,2.92,RU,1592427742,no hotel here
28,Kindu,-2.95,25.95,293.41,60,4.0,0.82,CD,1592427742,NGANDA MAZEMBE KINDU
29,Inongo,-1.95,18.27,294.75,59,1.0,1.24,CD,1592427424,no hotel here
...,...,...,...,...,...,...,...,...,...,...
197,Antalaha,-14.9,50.28,292.80,78,3.0,5.12,MG,1592427781,Lotus
198,Bayir,37.27,28.22,294.15,83,20.0,2.60,TR,1592427781,Zadegan Çorba Köfte
199,Soyo,-6.13,12.37,296.03,88,47.0,2.20,AO,1592427405,SoChot
200,Sarakhs,36.54,61.16,299.15,31,0.0,2.10,IR,1592427724,مرغ بریان رویال
201,Evensk,61.95,159.23,286.05,69,17.0,1.59,RU,1592427782,no hotel here
202,Boyolangu,-8.12,111.89,297.68,89,45.0,2.75,ID,1592427783,Wisata Kampung Air
203,Aktanysh,55.72,54.08,283.48,82,5.0,2.97,RU,1592427783,Mizgel
204,Cootamundra,-34.65,148.03,281.48,81,0.0,1.79,AU,1592427783,Planted Cootamundra
205,Aksarka,66.56,67.8,275.01,84,13.0,3.57,RU,1592427783,no hotel here
206,Lyuban',52.8,28.0,291.48,93,0.0,3.50,BY,1592427784,Kafe Svitanok
207,Port Lincoln,-34.73,135.87,286.37,63,8.0,8.99,AU,1592427430,Port Lincoln Hotel
208,Ros谩rio do Sul,-30.26,-54.91,294.01,80,4.0,5.30,BR,1592427785,Confectionery Dona Carolina
209,Kota Kinabalu,5.97,116.07,299.15,94,20.0,2.41,MY,1592427785,Evening Food Stalls
210,Ushtobe,45.25,77.98,289.03,56,4.0,4.58,KZ,1592427785,Akzhol
211,Kruisfontein,-34.0,24.73,285.04,41,0.0,2.62,ZA,1592427407,Mississippi Fried Chicken
212,Tatarsk,55.22,75.98,284.45,72,0.0,3.71,RU,1592427786,"""Edel'veys"""
213,Itarema,-2.92,-39.92,298.57,85,3.0,4.65,BR,1592427401,Oasis Restaurant and Inn
214,Cap Malheureux,-19.98,57.61,293.71,90,43.0,5.36,MU,1592427787,Wang Thai
215,Aitape,-3.14,142.35,297.98,83,0.0,1.93,PG,1592427787,no hotel here
216,Tiznit Province,29.58,-9.5,292.97,55,4.0,2.06,MA,1592427787,no hotel here
217,Novopokrovka,49.84,36.55,296.15,56,34.0,2.00,UA,1592427787,no hotel here
218,Gardez,33.6,69.23,289.34,30,0.0,2.13,AF,1592427788,خوندور رسټورانټ
219,Ben Gardane,33.14,11.22,299.81,42,0.0,6.13,TN,1592427788,Pizza Al Amir
220,Sechura,-5.56,-80.82,297.38,56,3.0,7.03,PE,1592427433,Loma Dorada ceviches y parrillas
221,Campo Maior,-4.83,-42.17,299.02,61,13.0,1.61,BR,1592427788,Misturinha
222,Karpathos,35.51,27.21,294.60,83,0.0,5.34,GR,1592427788,CIAO Restaurant
223,Inhambane,-23.86,35.38,292.51,82,29.0,6.18,MZ,1592427789,África Tropical
224,Phalaborwa,-23.94,31.14,287.15,76,25.0,3.10,ZA,1592427789,Roman's Pizza Phalaborwa
225,Kangaatsiaq,68.31,-53.46,275.40,89,22.0,4.04,GL,1592427789,no hotel here
226,San Vicente,-26.62,-54.13,292.93,77,0.0,2.26,AR,1592427606,Nuevo Restaurante la Terminal San Pedro

In [108]:
hotel_df = temp

In [112]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [111]:

locations = hotel_df[["Lat", "Lng"]]
import gmaps
gmaps.configure(api_key='AIzaSyAoZFHkCidaXiLGl3raC8vHIb6mnzRI51A')

nuclear_power_plants = [
    {'name': 'Atucha', 'location': (-34.0, -59.167), 'active_reactors': 1},
    {'name': 'Embalse', 'location': (-32.2333, -64.4333), 'active_reactors': 1},
    {'name': 'Armenia', 'location': (40.167, 44.133), 'active_reactors': 1},
    {'name': 'Br', 'location': (51.217, 5.083), 'active_reactors': 1},
    {'name': 'Doel', 'location': (51.333, 4.25), 'active_reactors': 4},
    {'name': 'Tihange', 'location': (50.517, 5.283), 'active_reactors': 3}
]

plant_locations = [plant['location'] for plant in nuclear_power_plants]
info_box_template = """
<dl>
<dt>Name</dt><dd>{name}</dd>
<dt>Number reactors</dt><dd>{active_reactors}</dd>
</dl>
"""
plant_info = [info_box_template.format(**plant) for plant in nuclear_power_plants]

marker_layer = gmaps.marker_layer(plant_locations, info_box_content=plant_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)
fig

In [ ]:
hotel_df['Lat'] = hotel_df['Lat'].apply(float)
hotel_df['Lng'] = hotel_df['Lng'].apply(float)

In [150]:
key1 = 'Hotel Name'
key2 = 'location'
key3 = 'City'
key4 = 'Country'
hotel_list = []
for i in range(len(hotel_df)):
    my_dict = {key1: hotel_df.iloc[i,9], key2: tuple(hotel_df.loc[i,:][1:3]),key3: hotel_df.iloc[i,0],key4: hotel_df.iloc[i,7]}
    hotel_list.append(my_dict)
hotel_list[0]

{'Hotel Name': 'Lanzazkoyen S.L.',
 'location': (28.5, -13.86),
 'City': 'Puerto del Rosario',
 'Country': 'ES'}

In [152]:
import gmaps
gmaps.configure(api_key='AIzaSyAoZFHkCidaXiLGl3raC8vHIb6mnzRI51A')

hotel_locations = [hotel['location'] for hotel in hotel_list]

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**hotel) for hotel in hotel_list]

marker_layer = gmaps.marker_layer(hotel_locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
they donot have hotel, I pick reseurant instead
# In the type parameter for place searches (Places API only), to restrict the results to places matching the specified type.
# accounting
# airport
# amusement_park
# aquarium
# art_gallery
# atm
# bakery
# bank
# bar
# beauty_salon
# bicycle_store
# book_store
# bowling_alley
# bus_station
# cafe
# campground
# car_dealer
# car_rental
# car_repair
# car_wash
# casino
# cemetery
# church
# city_hall
# clothing_store
# convenience_store
# courthouse
# dentist
# department_store
# doctor
# drugstore
# electrician
# electronics_store
# embassy
# fire_station
# florist
# funeral_home
# furniture_store
# gas_station
# gym
# hair_care
# hardware_store
# hindu_temple
# home_goods_store
# hospital
# insurance_agency
# jewelry_store
# laundry
# lawyer
# library
# light_rail_station
# liquor_store
# local_government_office
# locksmith
# lodging
# meal_delivery
# meal_takeaway
# mosque
# movie_rental
# movie_theater
# moving_company
# museum
# night_club
# painter
# park
# parking
# pet_store
# pharmacy
# physiotherapist
# plumber
# police
# post_office
# primary_school
# real_estate_agency
# restaurant
# roofing_contractor
# rv_park
# school
# secondary_school
# shoe_store
# shopping_mall
# spa
# stadium
# storage
# store
# subway_station
# supermarket
# synagogue
# taxi_stand
# tourist_attraction
# train_station
# transit_station
# travel_agency
# university
# veterinary_care
# zoo

In [ ]:
# Add marker layer ontop of heat map


# Display figure